// Generated by `wit-bindgen` 0.48.1. DO NOT EDIT!
#ifndef __BINDINGS_HOST_H
#define __BINDINGS_HOST_H
#ifdef __cplusplus
extern "C" {
#endif

#include <stdint.h>
#include <stdbool.h>
#include <stddef.h>

typedef struct host_string_t {
  uint8_t*ptr;
  size_t len;
} host_string_t;

// Imported Functions from `host`
extern void host_print(host_string_t *msg);

// Exported Functions from `host`
void exports_host_run(void);

// Helper Functions

// Sets the string `ret` to reference the input string `s` without copying it
void host_string_set(host_string_t *ret, const char*s);

// Creates a copy of the input nul-terminated string `s` and
// stores it into the component model string `ret`.
void host_string_dup(host_string_t *ret, const char*s);

// Deallocates the string pointed to by `ret`, deallocating
// the memory behind the string.
void host_string_free(host_string_t *ret);

#ifdef __cplusplus
}
#endif
#endif
